spring.application.name=engine-fleet-management

spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_management
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

server.port=8080
